# Generated by Django 4.1.3 on 2022-11-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=256)),
                ('date_at', models.CharField(max_length=256)),
                ('storage_id', models.IntegerField()),
                ('oklad', models.IntegerField()),
                ('percent', models.IntegerField()),
                ('premium', models.IntegerField()),
                ('fine', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'auto_salary',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField()),
                ('storage_id', models.IntegerField()),
            ],
            options={
                'db_table': 'blacklist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('url_api', models.CharField(blank=True, max_length=255, null=True)),
                ('key_api', models.CharField(blank=True, max_length=36, null=True)),
                ('key_updated_at', models.DateTimeField(blank=True, null=True)),
                ('login_api', models.CharField(blank=True, max_length=24, null=True)),
                ('pass_api', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'brand',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('is_remains', models.IntegerField()),
                ('is_sales', models.IntegerField()),
                ('is_income', models.IntegerField()),
            ],
            options={
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
                ('photo', models.IntegerField(blank=True, null=True)),
                ('fio', models.CharField(max_length=64)),
                ('birth_date', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(blank=True, max_length=24, null=True)),
                ('storage_id', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('first_work_day', models.CharField(blank=True, max_length=256, null=True)),
                ('oklad', models.IntegerField()),
                ('is_deleted', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('date_at', models.DateField()),
                ('storage_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('sum', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('is_bn', models.IntegerField()),
            ],
            options={
                'db_table': 'expenses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExpensesSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('input_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'expenses_source',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('amount', models.CharField(max_length=256)),
                ('difference', models.CharField(max_length=256)),
                ('fact', models.CharField(max_length=256)),
                ('garazh', models.IntegerField(blank=True, null=True)),
                ('esenina', models.IntegerField(blank=True, null=True)),
                ('nevkipelogo', models.IntegerField(blank=True, null=True)),
                ('cherkasskaya', models.IntegerField(blank=True, null=True)),
                ('chekistov', models.IntegerField(blank=True, null=True)),
                ('sormovskaya', models.IntegerField(blank=True, null=True)),
                ('itogo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('date_at', models.DateField()),
                ('storage_id', models.IntegerField()),
                ('sum_cash_morning', models.IntegerField()),
                ('sum_cash_end_day', models.IntegerField(blank=True, null=True)),
                ('total_cash', models.IntegerField(blank=True, null=True)),
                ('total_bn', models.IntegerField(blank=True, null=True)),
                ('total_market', models.IntegerField(blank=True, null=True)),
                ('total_day', models.IntegerField(blank=True, null=True)),
                ('calculated', models.IntegerField(blank=True, null=True)),
                ('difference', models.IntegerField(blank=True, null=True)),
                ('total_salary', models.IntegerField(blank=True, null=True)),
                ('total_expenses', models.IntegerField(blank=True, null=True)),
                ('payin', models.IntegerField(blank=True, null=True)),
                ('payout', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'money',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PayinText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'payin_text',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paymenttypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'PaymentTypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('date_at', models.DateField()),
                ('storage_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('comment', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'pays',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(max_length=64)),
                ('oklad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'positions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=256, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=256, null=True)),
                ('num', models.CharField(blank=True, max_length=256, null=True)),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('product_type', models.CharField(blank=True, max_length=256, null=True)),
                ('main_unit', models.CharField(blank=True, max_length=256, null=True)),
                ('product_category', models.CharField(blank=True, max_length=256, null=True)),
                ('supplier_id', models.CharField(max_length=256)),
                ('minimal', models.IntegerField(blank=True, null=True)),
                ('wanna_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('date_at', models.DateField()),
                ('storage_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('oklad', models.IntegerField()),
                ('percent', models.IntegerField()),
                ('premium', models.IntegerField()),
                ('month', models.CharField(blank=True, max_length=64, null=True)),
                ('days', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'salary',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('storage_id', models.CharField(max_length=256)),
                ('pointofsale', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=256)),
                ('yur_lico', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'storages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('date_at', models.DateField()),
                ('storage_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('position_id', models.IntegerField()),
                ('oklad', models.IntegerField()),
            ],
            options={
                'db_table': 'timetable',
                'managed': True,
            },
        ),
    ]
