from lk import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.defaults import page_not_found, server_error

app_name = "LK"

urlpatterns = [
    path('', views.lk, name="lk_lk"),
    path('money', views.money, name="lk_money"),
    path('timetable', views.timetable, name="lk_timetable"),
    path('salary', views.salary, name="lk_salary"),
    path('expenses', views.expenses, name="lk_expenses"),
    path('employee', views.employee, name="lk_employee"),
    path('employee/new', views.employee_new, name="lk_employee_new"),
    path('employee/edit', views.employee_edit, name="lk_employee_edit"),
    path('employee/save', views.employee_save, name="lk_employee_save"),
    path('<str:data>/delete', views.delete, name="lk_delete"),
    path('money/edit', views.money_edit, name="lk_money_edit"),
    path('salary/edit', views.salary_edit, name="lk_salary_edit"),
    path('salary/new', views.salary_new, name="lk_salary_new"),
    path('timetable/edit', views.timetable_edit, name="lk_timetable_edit"),
    path('timetable/new', views.timetable_new, name="lk_timetable_new"),
    path('expenses/new', views.expenses_new, name="lk_expenses_new"),
    path('expenses/edit', views.expenses_edit, name="lk_expenses_edit"),
    path('money/update', views.update_end_day, name="lk_update_end_day"),
    path('salary/calculation', views.salary_calculation, name="lk_salary_calculation"),
    path('salary/total_calculation', views.salary_total_calculation, name="lk_salary_total_calculation"),
    path('salary/employee_calculation', views.salary_employee_calculation, name="lk_salary_employee_calculation"),
    path('salary/update', views.salary_calculation_update, name="lk_salary_calculation_update"),
    path('salary/employee/send', views.salary_employee_send, name="lk_salary_employee_send"),
    path('fine', views.fine, name="lk_fine"),
    path('fine/save', views.fine_save, name="lk_fine_save"),
    path('new/fine/save', views.new_fine_save, name="lk_new_fine_save"),
    path('mysql/prepare', views.mysql_prepare, name="lk_mysql_prepare"),
    path('pays', views.pays, name="lk_pays"),
    path('blacklist', views.blacklist, name="lk_blacklist"),
    path('employee/comeback', views.employee_comeback, name="lk_employee_comeback"),
    path('pays/edit', views.pays_edit, name="lk_pays_edit"),
    path('pays/new', views.pays_new, name="pays_new"),
    path('bars', views.bars, name="lk_bars"),
    path('statement', views.bank_parser, name="bank_parser"),
    path('statement/cards', views.statement_cards, name="statement_cards"),
    path('employee_with_salary', views.employee_with_salary, name="employee_with_salary"),
    path('arrivals', views.arrivals, name="arrivals"),
    path('supplier_debt', views.supplier_debt, name="supplier_debt"),
    path('arrivals/new', views.beer_arrival_new, name="arrivals_new"),
    path('tovar_requests', views.tovar_requests, name="tovar_requests"),
    path('partners', views.partners, name="partners"),
    path('partners/edit', views.partners_edit, name="partners_edit"),
    path('arrivals/edit', views.arrivals_edit, name="arrivals_edit"),
    path('statement/cards/edit', views.cards_edit, name="cards_edit"),
    path('statement/edit', views.statement_edit, name="statement_edit"),
    path('statement/cards/sum', views.statement_cards_sum, name="statement_cards_sum"),
    path('arrivals/delete', views.arrivals_delete, name="arrivals_delete"),
    path('arrivals/copy', views.arrivals_copy, name="arrivals_copy"),
    path('revise', views.revise, name="revise"),
    path('tovar_requests/edit', views.tovar_requests_edit, name="tovar_requests_edit"),
]